# Generated by Django 5.1.7 on 2025-05-18 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='expedientes/archivos/%Y/%m/%d/')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('fecha_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReclamacion',
            fields=[
                ('id_det_recl', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('2105', 'Operaciones'), ('2103', 'Operaciones'), ('2106', 'Comercial'), ('2101', 'Operaciones'), ('2104', 'Daño a la Propiedad'), ('2110', 'Otros')], default='2105', max_length=4, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id_procedencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
                'ordering': ['id_procedencia'],
            },
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id_reclamacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('Lineas y Postes', 'Lineas y Postes'), ('Alumbrado Público', 'Alumbrado Público'), ('Comercial', 'Comercial'), ('Electrificación', 'Electrificación'), ('Daño a la Propiedad', 'Daño a la Propiedad'), ('Otros', 'Otros')], default='Lineas y Postes', max_length=100, unique=True, verbose_name='Reclamacion')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='El título debe ser un número de 4 dígitos.', regex='^[0-9]{4}$')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('resumen', models.TextField(blank=True)),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('importan', models.BooleanField(default=False)),
                ('clasificacion', models.CharField(choices=[('solicitud', 'Solicitud'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('denuncia', 'Denuncia')], default='queja', max_length=50, verbose_name='Clasificación')),
                ('ueb_obets', models.CharField(choices=[('UEB_Calimete', 'UEB OBET Calimete'), ('UEB_Cárdenas', 'UEB OBET Cárdenas'), ('UEB_Cienaga', 'UEB OBET Cienaga de Zapata'), ('UEB_Colón', 'UEB OBET Colón'), ('UEB_Jaguey', 'UEB OBET Jaguey Grande'), ('UEB_Jovellanos', 'UEB OBET Jovellanos'), ('UEB_Limonar', 'UEB OBET Limonar'), ('UEB_Arabos', 'UEB OBET Los Arabos'), ('UEB_Martí', 'UEB OBET Martí'), ('UEB_Matanzas', 'UEB OBET Matanzas'), ('UEB_Pedro_B', 'UEB OBET Pedro Betancourt'), ('UEB_Perico', 'UEB OBET Perico'), ('UEB_Unión', 'UEB OBET Unión de Reyes')], default='UEB_Calimete', max_length=50, verbose_name='Unidad Empresarial de Base')),
                ('evaluacion_gestion', models.CharField(blank=True, choices=[('-----', '-----'), ('solucionado', 'Solucionado'), ('pendiente_a_solucion', 'Pendiente a Solucion'), ('sin_solucion', 'Sin Solucion'), ('no_procede', 'No Procede')], default='-----', max_length=50, verbose_name='Evaluación de la Gestión')),
                ('resultado_gestion', models.CharField(blank=True, choices=[('-----', '-----'), ('con_razon', 'Con Razón'), ('razon_en_parte', 'Razón en Parte'), ('sin_razon', 'Sin Razón')], default='-----', max_length=50, verbose_name='Resultado de la Gestión')),
                ('clientes', models.ManyToManyField(related_name='expedientes', to='gestion.cliente')),
                ('estado_expediente', models.ForeignKey(default='Pendiente', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.estadoexpediente', verbose_name='Estado Expediente')),
            ],
        ),
    ]
