# Generated by Django 5.1.7 on 2025-03-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('resumen', models.TextField(blank=True)),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
