# Generated by Django 5.1.7 on 2025-03-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReclamacion',
            fields=[
                ('id_det_recl', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obets',
            fields=[
                ('id_obet', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id_procedencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id_reclamacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('resumen', models.TextField(blank=True)),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_complete', models.DateTimeField(null=True)),
                ('importan', models.BooleanField(default=False)),
                ('clientes', models.ManyToManyField(related_name='expedientes', to='gestion.cliente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.registro', verbose_name='Registro Anual')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.expediente', verbose_name='Expediente Asociado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestion.municipio', verbose_name='Municipio'),
        ),
    ]
