# Generated by Django 5.1.7 on 2025-03-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_complete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='importan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
