# Generated by Django 5.1.7 on 2025-05-18 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.expediente', verbose_name='Archivos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='gestion.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='detalle_reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones', to='gestion.detallereclamacion', verbose_name='Detalle de Reclamación'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.reclamacion', verbose_name='Reclamación Asociada'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.registro', verbose_name='Registro Anual'),
        ),
    ]
