# Generated by Django 5.1.7 on 2025-05-20 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.estadoexpediente', verbose_name='Estado Expediente'),
        ),
    ]
