# Generated by Django 5.1.7 on 2025-03-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_expediente_fecha_complete_expediente_importan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
