# Generated by Django 5.1.7 on 2025-04-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_delete_clasificacion_delete_obets_delete_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='archivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.archivo', verbose_name='Archivo Asociado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.estadoexpediente', verbose_name='Estado del Expediente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='resultado_gestion',
            field=models.CharField(choices=[('con_razon', 'Con Razón'), ('razon_en_parte', 'Razón en Parte'), ('sin_razon', 'Sin Razón')], default='con_razon', max_length=50, verbose_name='Resultado de la Gestión'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='detalle_reclamacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones', to='gestion.detallereclamacion', verbose_name='Detalle de Reclamación'),
            preserve_default=False,
        ),
    ]
