# Generated by Django 5.1.7 on 2025-05-20 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_expediente_estado_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='clasificacion',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('denuncia', 'Denuncia')], max_length=50, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.procedencia', verbose_name='Procedencia'),
        ),
    ]
