# Generated by Django 5.1.7 on 2025-05-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_expediente_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='importan',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='evaluacion_gestion',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('solucionado', 'Solucionado'), ('pendiente_a_solucion', 'Pendiente a Solucion'), ('sin_solucion', 'Sin Solucion'), ('no_procede', 'No Procede')], max_length=50, null=True, verbose_name='Evaluación de la Gestión'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='resultado_gestion',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('con_razon', 'Con Razón'), ('razon_en_parte', 'Razón en Parte'), ('sin_razon', 'Sin Razón')], max_length=50, null=True, verbose_name='Resultado de la Gestión'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
