# Generated by Django 5.1.7 on 2025-04-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_expediente_archivo_expediente_estado_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='reclamacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.reclamacion', verbose_name='Reclamación Asociada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.archivo', verbose_name='Archivo Asociado'),
        ),
    ]
