# Generated by Django 5.1.7 on 2025-05-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_expediente_importan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.estadoexpediente', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='evaluacion_gestion',
            field=models.CharField(blank=True, choices=[('solucionado', 'Solucionado'), ('pendiente_a_solucion', 'Pendiente a Solucion'), ('sin_solucion', 'Sin Solucion'), ('no_procede', 'No Procede')], max_length=50, null=True, verbose_name='Evaluación de la Gestión'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='resultado_gestion',
            field=models.CharField(blank=True, choices=[('con_razon', 'Con Razón'), ('razon_en_parte', 'Razón en Parte'), ('sin_razon', 'Sin Razón')], max_length=50, null=True, verbose_name='Resultado de la Gestión'),
        ),
    ]
