# Generated by Django 5.1.7 on 2025-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_procedencia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='nombre',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoexpediente',
            name='estado',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='clientes',
            field=models.ManyToManyField(related_name='expedientes', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='obets',
            name='nombre',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
