# Generated by Django 5.1.7 on 2025-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_expediente_reclamacion_alter_expediente_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombre del Archivo'),
            preserve_default=False,
        ),
    ]
