# Generated by Django 5.1.7 on 2025-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_expediente_estado_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
