# Generated by Django 5.1.7 on 2025-04-18 03:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_expediente_archivo_archivo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoexpediente',
            old_name='id_archivo',
            new_name='id_estado',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El carnet debe contener exactamente 11 dígitos y solo números.', regex='^\\d{11}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion.estadoexpediente', verbose_name='Estado Expediente'),
        ),
    ]
