# Generated by Django 5.1.7 on 2025-04-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_id_archivo_estadoexpediente_id_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ueb_obets',
            field=models.CharField(choices=[('UEB_Calimete', 'UEB Calimete'), ('UEB2_Cárdenas', 'Unidad Empresarial de Base Cárdenas'), ('UEB3_Cienaga', 'Unidad Empresarial de Base Cienaga de Zapata'), ('UEB4_Colón', 'Unidad Empresarial de Base Colón'), ('UEB5_Jaguey', 'Unidad Empresarial de Base Jaguey Grande'), ('UEB6_Jovellanos', 'Unidad Empresarial de Base Jovellanos'), ('UEB7_Limonar', 'Unidad Empresarial de Base Limonar'), ('UEB8_Arabos', 'Unidad Empresarial de Base Los Arabos'), ('UEB9_Martí', 'Unidad Empresarial de Base Martí'), ('UEB10_Matanzas', 'Unidad Empresarial de Base Matanzas'), ('UEB11_Pedro_B', 'Unidad Empresarial de Base Pedro Betancourt'), ('UEB12_Perico', 'Unidad Empresarial de Base Perico'), ('UEB13_Unión', 'Unidad Empresarial de Base Unión de Reyes')], default='UEB_Matanzas', max_length=50, verbose_name='Unidad Empresarial de Base'),
        ),
    ]
