# Generated by Django 5.1.7 on 2025-05-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_cliente_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='respuesta',
        ),
        migrations.CreateModel(
            name='RespuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.expediente')),
            ],
        ),
    ]
