# Generated by Django 5.1.7 on 2025-05-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_expediente_respuesta_respuestacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.expediente', verbose_name='Archivos'),
        ),
        migrations.AlterField(
            model_name='respuestacliente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='gestion.expediente', verbose_name='Respuestas'),
        ),
    ]
