# Generated by Django 5.1.7 on 2025-04-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_cliente_carnet_alter_expediente_ueb_obets'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallereclamacion',
            name='codigo',
            field=models.CharField(choices=[('2105', 'Operaciones'), ('2103', 'Operaciones'), ('2106', 'Comercial'), ('2101', 'Operaciones'), ('2104', 'Daño a la Propiedad'), ('2105', 'Operaciones')], default='2105', max_length=4, verbose_name='Código'),
        ),
    ]
