# Generated by Django 5.1.7 on 2025-05-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_detallereclamacion_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedencia',
            options={'ordering': ['id_procedencia'], 'verbose_name': 'Procedencia', 'verbose_name_plural': 'Procedencias'},
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='fecha_complete',
            new_name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestion.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ueb_obets',
            field=models.CharField(choices=[('UEB_Calimete', 'UEB Calimete'), ('UEB2_Cárdenas', 'Unidad Empresarial de Base Cárdenas'), ('UEB3_Cienaga', 'Unidad Empresarial de Base Cienaga de Zapata'), ('UEB4_Colón', 'Unidad Empresarial de Base Colón'), ('UEB5_Jaguey', 'Unidad Empresarial de Base Jaguey Grande'), ('UEB6_Jovellanos', 'Unidad Empresarial de Base Jovellanos'), ('UEB7_Limonar', 'Unidad Empresarial de Base Limonar'), ('UEB8_Arabos', 'Unidad Empresarial de Base Los Arabos'), ('UEB9_Martí', 'Unidad Empresarial de Base Martí'), ('UEB10_Matanzas', 'Unidad Empresarial de Base Matanzas'), ('UEB11_Pedro_B', 'Unidad Empresarial de Base Pedro Betancourt'), ('UEB12_Perico', 'Unidad Empresarial de Base Perico'), ('UEB13_Unión', 'Unidad Empresarial de Base Unión de Reyes')], default='UEB_Calimete', max_length=50, verbose_name='Unidad Empresarial de Base'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
