# Generated by Django 5.1.7 on 2025-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_expediente_evaluacion_gestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacliente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Pendiente?'),
        ),
    ]
