# Generated by Django 5.1.7 on 2025-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_procedencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoexpediente',
            name='estado',
            field=models.CharField(max_length=50, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='descripcion',
            field=models.CharField(choices=[('Lineas y Postes', 'Lineas y Postes'), ('Alumbrado Público', 'Alumbrado Público'), ('Comercial', 'Comercial'), ('Electrificación', 'Electrificación'), ('Daño a la Propiedad', 'Daño a la Propiedad'), ('Otros', 'Otros')], default='Lineas y Postes', max_length=100, unique=True, verbose_name='Reclamacion'),
        ),
    ]
