# Generated by Django 5.1.7 on 2025-06-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_respuestacliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='gestion.reclamacion', verbose_name='Reclamación Asociada'),
        ),
    ]
