# Generated by Django 5.1.7 on 2025-06-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_expediente_reclamacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='clientes',
            field=models.ManyToManyField(related_name='expediente', to='gestion.cliente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='gestion.estadoexpediente', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='gestion.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='gestion.registro', verbose_name='Registro Anual'),
        ),
    ]
