# Generated by Django 5.1.7 on 2025-05-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_expediente_user_alter_registro_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='archivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestion.archivo', verbose_name='Archivos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='gestion.municipio', verbose_name='Municipio'),
        ),
    ]
