# Generated by Django 5.1.7 on 2025-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_expediente_clientes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestacliente',
            unique_together={('expediente', 'cliente')},
        ),
    ]
