# Generated by Django 5.1.7 on 2025-06-19 21:29

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_respuestacliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=gestion.models.archivo_expediente_upload_to),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
